
var shuffleSequence = seq("consent", "intro", "p", "begin", sepWith("sep", rshuffle(rshuffle("noncollective", "collective", "filler"))), "debrief");
var practiceItemTypes = ["p"];

var defaults = [
    "Separator", {
        transfer: 500,
        hideProgressBar: true,
        normalMessage: "+"
    },
    "Message", {
        transfer: "keypress",
        hideProgressBar: true
    },
    "AcceptabilityJudgment", {
        q: '',
        as: ["1", "2", "3", "4", "5", "6", "7"],
        presentAsScale: true,
        instructions: "Use number keys or click boxes to answer.",
        leftComment: "(Bad)", rightComment: "(Good)"
    },
    "Form", { hideProgressBar: true }

];

var items = [
	["consent", "Form", {
        html: { include: "consent.html" },
		validators: {age: function (s) { if (s.match(/^\d+$/)) return true;
							else return "Bad value for age"; }}
    } ],

	["intro", "Message", {html: { include: "intro.html" }}],

	["p", "AcceptabilityJudgment", {s: "Gary ran that he ate a piece of cake."}],
	["p", "AcceptabilityJudgment", {s: "Stacy built a house for him."}],
	["p", "AcceptabilityJudgment", {s: "I failed going to the store."}],

	["begin", "Message", {
				html: { include: "begin.html" },
				} ],

    ["sep", "Separator", { }],

    ["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken decided to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry decided to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Ken said that Betty decided to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel decided to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken decided to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry decided to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Ken said that Betty decided to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel decided to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Erin said that Sal was afraid to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Ken said that Betty was afraid to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan was afraid to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mat said that Erin was afraid to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Erin said that Sal was afraid to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Ken said that Betty was afraid to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan was afraid to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mat said that Erin was afraid to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty and Fred decided to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal and Rita decided to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet and Mike decided to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken and Jill decided to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol and Hal decided to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val and Barbara decided to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry and Beth decided to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan and Guy decided to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty and Fred was afraid to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal and Rita was afraid to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet and Mike was afraid to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken and Jill was afraid to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol and Hal was afraid to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val and Barbara was afraid to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry and Beth was afraid to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan and Guy was afraid to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol preferred Hal to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mel said that Mat preferred Daphne to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel preferred Larry to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken preferred Jill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal preferred Rita to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet preferred Mike to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry preferred Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan preferred Guy to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol refused Hal to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mel said that Mat refused Daphne to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel refused Larry to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken refused Jill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal refused Rita to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet refused Mike to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry refused Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan refused Guy to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol promised Hal to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mel said that Mat promised Daphne to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel promised Larry to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken promised Jill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal promised Rita to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet promised Mike to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry promised Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan promised Guy to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol was eager Hal to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mel said that Mat was eager Daphne to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel was eager Larry to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken was eager Jill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal was eager Rita to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet was eager Mike to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry was eager Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan was eager Guy to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val was ready for Barbara to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin was ready for Bill to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan was ready for Guy to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal was ready for Rita to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel was ready for Larry to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet was ready for Mike to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry was ready for Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken was ready for Jill to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val planned for Barbara to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin planned for Bill to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan planned for Guy to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal planned for Rita to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel planned for Larry to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet planned for Mike to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry planned for Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken planned for Jill to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val offered for Barbara to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin offered for Bill to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan offered for Guy to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal offered for Rita to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel offered for Larry to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet offered for Mike to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry offered for Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken offered for Jill to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val expected for Barbara to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin expected for Bill to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan expected for Guy to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal expected for Rita to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel expected for Larry to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet expected for Mike to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry expected for Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken expected for Jill to support the child.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken offered to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mat said that Erin offered to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mel said that Mat offered to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet offered to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken offered to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mat said that Erin offered to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mel said that Mat offered to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet offered to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken preferred to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet preferred to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel preferred to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Betty said that Val preferred to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken preferred to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet preferred to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel preferred to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Betty said that Val preferred to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jerry said that Carol refused to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel refused to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken refused to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet refused to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jerry said that Carol refused to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel refused to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken refused to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet refused to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel was eager to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jerry said that Carol was eager to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mat said that Erin was eager to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry was eager to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel was eager to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jerry said that Carol was eager to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mat said that Erin was eager to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry was eager to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet was happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken supported the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan took yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry rented an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet was happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken supported the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan took yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry rented an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mel said that Mat planned to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry planned to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet planned to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan planned to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mel said that Mat planned to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry planned to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet planned to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan planned to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken expected to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel expected to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Ken said that Betty expected to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Erin said that Sal expected to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken expected to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel expected to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Ken said that Betty expected to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Erin said that Sal expected to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Erin said that Sal was ready to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel was ready to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Ken said that Betty was ready to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mat said that Erin was ready to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Erin said that Sal was ready to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel was ready to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Ken said that Betty was ready to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mat said that Erin was ready to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken promised to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mel said that Mat promised to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jerry said that Carol promised to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan promised to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken promised to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mel said that Mat promised to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jerry said that Carol promised to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan promised to rent an apartment in Baltimore.'}],
	[["debrief", 1], "Form", {html: { include: "debrief0.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief1.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief2.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief3.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief4.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief5.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief6.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief7.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief8.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief9.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief10.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief11.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief12.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief13.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief14.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief15.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief16.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief17.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief18.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief19.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief20.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief21.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief22.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief23.html" }}]

];
