
var shuffleSequence = seq("consent", "intro", "p", "begin", sepWith("sep", rshuffle(rshuffle("noncollective", "collective", "filler")), "debrief"));
var practiceItemTypes = ["p"];

var defaults = [
    "Separator", {
        transfer: 500,
        hideProgressBar: true,
        normalMessage: "+"
    },
    "Message", {
        transfer: "keypress",
        hideProgressBar: true
    },
    "AcceptabilityJudgment", {
        q: '',
        as: ["1", "2", "3", "4", "5", "6", "7"],
        presentAsScale: true,
        instructions: "Use number keys or click boxes to answer.",
        leftComment: "(Bad)", rightComment: "(Good)"
    },
    "Form", { hideProgressBar: true }

];

var items = [
	["consent", "Form", {
        html: { include: "consent.html" },
		validators: {age: function (s) { if (s.match(/^\d+$/)) return true;
							else return "Bad value for age"; }}
    } ],

	["intro", "Message", {html: { include: "intro.html" }}],

	["p", "AcceptabilityJudgment", {s: "Gary ran that he ate a piece of cake."}],
	["p", "AcceptabilityJudgment", {s: "Stacy built a house for him."}],
	["p", "AcceptabilityJudgment", {s: "I failed going to the store."}],

	["begin", "Message", {
				html: { include: "begin.html" },
				} ],

    ["sep", "Separator", { }],

    ["collective", "AcceptabilityJudgment", {s: 'Betty said that Val loved to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Ken said that Betty loved to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry loved to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan loved to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Betty said that Val loved to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Ken said that Betty loved to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry loved to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan loved to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan managed to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mel said that Mat managed to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Erin said that Sal managed to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry managed to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan managed to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mel said that Mat managed to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Erin said that Sal managed to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry managed to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Erin said that Sal tried to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet tried to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel tried to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Betty said that Val tried to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Erin said that Sal tried to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet tried to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel tried to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Betty said that Val tried to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken and Jill began to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal and Rita began to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val and Barbara began to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet and Mike began to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mel said that Mat and Daphne began to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel and Larry began to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin and Bill began to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol and Hal began to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken and Jill was likely to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal and Rita was likely to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val and Barbara was likely to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet and Mike was likely to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mel said that Mat and Daphne was likely to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel and Larry was likely to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin and Bill was likely to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol and Hal was likely to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan needed Guy to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty needed Fred to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel needed Larry to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry needed Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol needed Hal to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken needed Jill to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin needed Bill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet needed Mike to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan wanted Guy to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty wanted Fred to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel wanted Larry to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry wanted Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol wanted Hal to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken wanted Jill to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin wanted Bill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet wanted Mike to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan intended Guy to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty intended Fred to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel intended Larry to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry intended Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol intended Hal to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken intended Jill to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin intended Bill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet intended Mike to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Val said that Jan managed Guy to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty managed Fred to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel managed Larry to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jan said that Jerry managed Beth to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol managed Hal to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken managed Jill to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin managed Bill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet managed Mike to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel tried for Larry to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty tried for Fred to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol tried for Hal to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin tried for Bill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet tried for Mike to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val tried for Barbara to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal tried for Rita to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken tried for Jill to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel claimed for Larry to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty claimed for Fred to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol claimed for Hal to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin claimed for Bill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet claimed for Mike to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val claimed for Barbara to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal claimed for Rita to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken claimed for Jill to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel hoped for Larry to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty hoped for Fred to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol hoped for Hal to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin hoped for Bill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet hoped for Mike to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val hoped for Barbara to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal hoped for Rita to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken hoped for Jill to support the child.'}],
	["filler", "AcceptabilityJudgment", {s: 'Dan said that Mel loved for Larry to support the child together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Ken said that Betty loved for Fred to take yoga classes together.'}],
	["filler", "AcceptabilityJudgment", {s: 'Jerry said that Carol loved for Hal to be happy alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Mat said that Erin loved for Bill to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Sal said that Harriet loved for Mike to take yoga classes alone.'}],
	["filler", "AcceptabilityJudgment", {s: 'Betty said that Val loved for Barbara to be happy.'}],
	["filler", "AcceptabilityJudgment", {s: 'Erin said that Sal loved for Rita to rent an apartment in Baltimore.'}],
	["filler", "AcceptabilityJudgment", {s: 'Carol said that Ken loved for Jill to support the child.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel began to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet began to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Betty said that Val began to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry began to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel began to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet began to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Betty said that Val began to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry began to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel was likely to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan was likely to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken was likely to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry was likely to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel was likely to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan was likely to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken was likely to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry was likely to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mat said that Erin hoped to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet hoped to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Betty said that Val hoped to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mel said that Mat hoped to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mat said that Erin hoped to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet hoped to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Betty said that Val hoped to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mel said that Mat hoped to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry needed to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Mat said that Erin needed to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Erin said that Sal needed to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel needed to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry needed to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Mat said that Erin needed to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Erin said that Sal needed to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel needed to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet was happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken supported the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan took yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry rented an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet was happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken supported the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan took yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry rented an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry claimed to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Ken said that Betty claimed to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jerry said that Carol claimed to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Betty said that Val claimed to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry claimed to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Ken said that Betty claimed to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jerry said that Carol claimed to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Betty said that Val claimed to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Sal said that Harriet wanted to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jerry said that Carol wanted to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Erin said that Sal wanted to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Betty said that Val wanted to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Sal said that Harriet wanted to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jerry said that Carol wanted to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Erin said that Sal wanted to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Betty said that Val wanted to rent an apartment in Baltimore.'}],
	["collective", "AcceptabilityJudgment", {s: 'Val said that Jan intended to be happy together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Carol said that Ken intended to support the child together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Dan said that Mel intended to take yoga classes together.'}],
	["collective", "AcceptabilityJudgment", {s: 'Jan said that Jerry intended to rent an apartment in Baltimore together.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Val said that Jan intended to be happy.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Carol said that Ken intended to support the child.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Dan said that Mel intended to take yoga classes.'}],
	["noncollective", "AcceptabilityJudgment", {s: 'Jan said that Jerry intended to rent an apartment in Baltimore.'}],
	[["debrief", 1], "Form", {html: { include: "debrief0.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief1.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief2.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief3.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief4.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief5.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief6.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief7.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief8.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief9.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief10.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief11.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief12.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief13.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief14.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief15.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief16.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief17.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief18.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief19.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief20.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief21.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief22.html" }}],
	[["debrief", 1], "Form", {html: { include: "debrief23.html" }}]

];
